books_storage/books_storage/books/urls.py
from django.urls import path
from .views import index, create_book, edit_book

urlpatterns = [
    path("", index, name="index"),
    path("create/", create_book, name="create"),
    path("edit/<int:pk>", edit_book, name="edit"),
]

books_storage/books_storage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("books_storage.books.urls"))
]

books_storage/books_storage/books/models.py
from django.core.validators import MinValueValidator
from django.db import models

# Create your models here.
"""
title – CharField with max-length of 20
pages – IntegerField with default value of 0
description – CharField with max length of 100 and empty string as a default value
author – CharField with max length of 20
"""


class Book(models.Model):
    title = models.CharField(
        max_length=20,
    )
    pages = models.IntegerField(
        validators=[
            MinValueValidator(1)
        ]
    )
    description = models.CharField(
        max_length=100,
        default=""
    )
    author = models.CharField(
        max_length=20,
    )

books_storage/books_storage/books/forms.py
from django import forms
from .models import Book

"""
title – TextInput with class form-control
pages – NumberInput with class form-control
author – TextInput with class form-control
description – Textarea with class form-control
"""


class BookModelForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'pages': forms.NumberInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                }
            ),
            'author': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

books_storage/books_storage/books/views.py
from django.shortcuts import render, redirect
from .forms import BookModelForm
from .models import Book


# Create your views here.
def show_book_form(req, form, temp):
    context = {
        'form': form,
    }
    return render(req, temp, context)


def save_book(req, form, red, temp):
    if form.is_valid():
        form.save()
        return redirect(red)
    return show_book_form(req, form, temp)


def index(req):
    context = {
        'books': Book.objects.all()
    }
    return render(req, "index.html", context)


def create_book(req):
    if req.method == 'GET':
        form = BookModelForm()
        return show_book_form(req, form, 'create.html')
    form = BookModelForm(req.POST)
    return save_book(req, form, 'index', 'create.html')


def edit_book(req, pk):
    book = Book.objects.get(pk=pk)
    if req.method == 'GET':
        form = BookModelForm(
            initial=book.__dict__,
        )
        return show_book_form(req, form, 'edit.html')
    form = BookModelForm(
        req.POST,
        instance=book,
    )
    return save_book(req, form, 'index', 'edit.html')

books_storage/templates/create.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <title>Model Forms Demo</title>
</head>
<body>
    <h1 class="display-4 text-center">Please fill out the form!</h1>
    <form method="post" class="m-auto w-25">
        {% csrf_token %}
        {{ form.errors }}
        <div class="form-group">
            <label for="id_title">Title</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_description">Description</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_pages">Pages</label>
            {{ form.pages }}
        </div>
        <div class="form-group">
            <label for="id_author">Author</label>
            {{ form.author }}
        </div>
        <button type="submit" class="btn btn-primary mx-auto">Submit</button>
    </form>
</body>
</html>

books_storage/templates/edit.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <title>Model Forms Demo</title>
</head>
<body>
    <h1 class="display-4 text-center">Edit the book</h1>
    <form method="post" class="m-auto w-25">
        {% csrf_token %}
        {{ form.errors }}
        <div class="form-group">
            <label for="id_title">Title</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_description">Description</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_pages">Pages</label>
            {{ form.pages }}
        </div>
        <div class="form-group">
            <label for="id_author">Author</label>
            {{ form.author }}
        </div>
        <button type="submit" class="btn btn-primary mx-auto">Edit</button>
    </form>
</body>
</html>

books_storage/templates/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <title>Model Forms Demo</title>
</head>
<body>
    <a class="text-light btn btn-success mt-2 ml-2" href="{% url 'create' %}">Create new Book</a>
    <p class="display-4 mt-2 ml-2">All books</p>
    <div class="d-flex justify-content-start">
        {% for book in books %}
        <div class="card m-2" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ book.author }}</h6>
                <p class="card-text">{{ book.description }}</p>
                <h6 class="card-subtitle mb-2 text-muted">{{ book.pages }} pages</h6>
                <a class="text-light btn btn-primary" href="{% url 'edit' book.pk %}">Edit</a>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>